wait for dpkg in case it is still on

diff --git a/crossbuilder b/crossbuilder
--- a/crossbuilder
+++ b/crossbuilder
@@ -282,6 +282,7 @@ new_container () {
         exec_container_root "sed -i 's/ENV_PATH.*PATH=/ENV_PATH\tPATH=\/usr\/lib\/ccache:/' /etc/login.defs"
         # wait for the container's network connection
         check_for_container_network
+        check_for_dpkg_available
         exec_container_root apt update
         exec_container_root apt install -y sudo debhelper ccache software-properties-common devscripts
         exec_container_root adduser $USERNAME sudo
@@ -487,7 +488,22 @@ check_for_container_network() {
         echo "${ERROR_COLOR}Container is not connected to the Internet.${NC}"
         exit 1
     fi
+}
 
+check_for_dpkg_available() {
+    DPKG_AVAILABLE=0
+    for i in `seq 1 60`
+    do
+        if exec_container test ! -e /var/lib/dpkg/lock; then
+            DPKG_AVAILABLE=1
+            break
+        fi
+        sleep 1
+    done
+    if [ $DPKG_AVAILABLE -ne 1 ] ; then
+        echo "${ERROR_COLOR}Container dpkg locked. /var/lib/dpkg/lock still exists after one minute. Giving up.${NC}"
+        exit 1
+    fi
 }
 
 check_for_device_network() {
